PKG_CONFIG=${OECORE_NATIVE_SYSROOT}/usr/bin/pkg-config

OBJ=USB31_TX_COMPLIANCE.o

USB31_TX_COMPLIANCE: $(OBJ)
	$(CC) $(OBJ) -lusb-1.0 -o USB31_TX_COMPLIANCE

USB31_TX_COMPLIANCE.o: USB31_TX_COMPLIANCE.c
	$(CC) -O2 -c USB31_TX_COMPLIANCE.c `${PKG_CONFIG} --libs --cflags libusb-1.0`

clean :
	rm *.o USB31_TX_COMPLIANCE
